var ActionType = {
  ADD_LOCATION: 'ADD_LOCATION',
  PLACE_CHANGED: 'PLACE_CHANGED',
  GROUPS: {
    ADD_GROUP: 'ADD_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',
    SELECT_GROUP: 'SELECT_GROUP',
    ADD_PLACE_TO_GROUP: 'ADD_PLACE_TO_GROUP',
    REMOVE_PLACE_FROM_GROUP: 'REMOVE_PLACE_FROM_GROUP'
  }
}

export default ActionType;
